### ISSUE TITLE
Hiding satellites with 0 signal strength is wrong

### ISSUE THREAD

**Issue by mlehtima** [direc85/sailfish-gpsinfo#11]
I find it a very bad idea to hide satellites with 0 signal strength. I think the change should be reverted and all satellites shown in the app.

**Comment by direc85** [comment]
The change makes little difference with Jolla 1, as the behavior doesn't change (except the counting is wrong with SFOS 2.2 for some reason, but it's a separate issue). I consider the zero-strength satellites to be unwanted noise that can be eliminated safely. A satellite with zero signal strength is as good as no satellite at all, as the device just hopes it will eventually hear something. What does the user gain by being shown all that data? Why exactly is hiding them a bad idea?

If there is a good reason to display the data, other than the graphs looking more clear, I'm ready to at least turn it into a setting at least.

Part of the same issue is now ignoring the signal strength value zero when deciding the colors for the bars and satellite signs. What are your opinions over that?

**Comment by mlehtima** [comment]
I was comparing the performance of getting location and how well the device sees satellites on several devices when the lack of showing everything made that impossible and I had to use CSD tool instead. I consider this app more like a debugging tool so not showing everything is quite the opposite to the purpose I see for the app. At least an option to enable all should be added if the old way is not wanted as the default behaviour.

I saw nothing wrong in the linked issue. The real values in such a situation could be seen in CSD tool which shows all visible satellites and their basic data.

**Comment by Olf0** [comment]
Thank you very much @direc85, displaying satellites with zero signal strength (by default) is working fine with GPSInfo 0.13 (and presumably 0.12).
Switching "Show empty channels" off in the Settings nicely restores the old behaviour.

#### Side note:
I wonder why my Xperia X (SFOS 3.2.1) seems to strongly prefer to lock on satellites with a weak signal strength (i.e., the ones displayed in red and brown hues) while it almost never uses the ones with a good signal strength (displayed in green hues).

Examples (taken without zero strength satellites displayed): 
* ![Screenshot_20200105_003](https://user-images.githubusercontent.com/16547876/71782883-81cb0580-2fdf-11ea-99b1-4ab0f88ec567.png)
* ![Screenshot_20200105_001](https://user-images.githubusercontent.com/16547876/71782888-8c859a80-2fdf-11ea-86ad-71ffa4b8715d.png)

Cross-checking with GPSInfo 0.11 on a Jolla 1 (SFOS 2.2.1) provides exactly the same result:
* ![Screenshot_20200105_001](https://user-images.githubusercontent.com/16547876/71782990-feaaaf00-2fe0-11ea-8d05-81bcd654853d.png)
* ![Screenshot_20200105_004](https://user-images.githubusercontent.com/16547876/71782997-12561580-2fe1-11ea-9ba6-d596bcd61407.png)

**Comment by direc85** [comment]
I implemented a setting for this and made it default to showing all channels, so I'm closing this as fixed. One thing it results into is unusable bar graph:

![messy_bars](https://user-images.githubusercontent.com/12432962/71784700-dcc02500-2ffe-11ea-95e9-f58be5a4f428.jpg)
(pardon the language ;)

I'm planning the graph to hide all zero-strength channels in every case. @mlehtima What is your opinion on this? Should the graph still show *all* channels nevertheless? I would guess that the amount of such channels (44 in the screenshot) is enough.

@Olf0 That's very interesting behavior. I think it's because of the Xperia X firmware doing its buggy thing, but that is really something I can't affect. Oh well, time to flash my Xperia X with SFOS again to test it!

**Comment by Olf0** [comment]
1. Well, technically everything is fine:
   ![Screenshot_20200105_005](https://user-images.githubusercontent.com/16547876/71785006-e3e53400-2ffa-11ea-8ad7-469a226020ac.png)
   (See all those zero signal strength satellites nicely displayed.)<br/>
   It is just that the numbering of the x-axis "collapses" (i.e. the numbers overlap too much to remain readable), when too many satellites are displayed on the bar graph page.
   This situation can always arise, regardless of "zero strength" satellites being displayed or not.  Displaying the "zero strength" satellites just raises the number of depicted satellites, causing this to occur more easily.
   There already is an algorithm reducing the amount of numbers displayed on the x-axis, but it seems to cease scaling (i.e., to further reduce the amount of numbers) at some point.
   Hence it might rather make sense to try improving this algorithm instead of not providing the complete information / picture (which is detrimental for e.g. debugging, as @mlehtima already [pointed out](https://github.com/direc85/harbour-gpsinfo/issues/11#issuecomment-561343767)).<br />
   Though as an additional and easy/ quick measure, you may consider to default the "Show empty channels" setting to "No" for fresh installations (or even set it *once* to "No" for all, including extant installations solely in the next update).
Maybe this solution is already sufficient to satisfy all considerations WRT this issue.

2. No, as written and depicted, this is **not** a firmware specific behaviour:
   It occurs on an Xperia X with SFOS 3.2.1 and a Jolla 1 with SFOS 2.1.1 alike (see screenshots, above).<br />
   I will try to cross-check with the CSD-tool, when I have some time to spend.

**Comment by mlehtima** [comment]
@direc85 I think the graph can skip showing the satellites with zero signal strength if that is wanted or at least do something to the shown values. The main thing for me is that the main page now again shows all satellites in view, for the graph showing all is not that important. Also just doing something to the x-axis will never be very easy as there can be a lot of satellites with non-zero signal strength as mentioned in previous comment and if you remove some values from the x-axis then it's going to be a bit more difficult to interpret the data.
