### ISSUE TITLE
binding loop errors

### ISSUE THREAD

**Issue by sbridger** [direc85/sailfish-gpsinfo#24]
Don't understand why
```
SatelliteBarchartPage: Binding loop detected for property "status"
/usr/share/harbour-gpsinfo/qml/harbour-gpsinfo.qml:12: QML SatelliteBarchartPage: Binding loop detected for property "status"
```

all pages seem to do it.

**Comment by direc85** [comment]
I noticed that, too. I have no idea how or why it happens. I don't even set its value anywhere...

It can be a Qt/SFOS bug, too. I'll have to test it using older SDKs. It's trivial to add 3.x versions, and I have 2.2.1 already at hand. Let's take a good look first.

The whole arrangement was done because I wanted bar charts on the left side of MainPage, and thr radar on the right. I thought it was cool, and it was a good learning exercise, too :)

**Comment by sbridger** [comment]
Yes I've created a binding error of my own that I don't understand. I am trying to get my head around how properties, js functions, the name space, etc all work together.

**Comment by direc85** [comment]
I'm, like, 99% sure that the binding error was there before, so please double check it with my master branch, too, before banging your head against the wall for nothing. Been there, done that... 🤦

**Comment by sbridger** [comment]
I've fixed my binding loop errors.

I tried replacing the word "status" with "true"  throughout satelliteinfo.qml.
It had no effect, the binding error is still there. (not that I could see any reason why it should..)
